// Generated by Xata Codegen 0.30.0. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "users",
    columns: [
      { name: "email", type: "text" },
      { name: "financial-advice", type: "bool", defaultValue: "false" },
      { name: "future-plan", type: "bool", defaultValue: "false" },
      { name: "goal-progress", type: "bool", defaultValue: "false" },
      { name: "money-habits", type: "bool", defaultValue: "false" },
      { name: "get-organized", type: "bool", defaultValue: "false" },
      { name: "reason", type: "text" },
      { name: "save-more", type: "bool", defaultValue: "false" },
      { name: "invest-smarter", type: "bool", defaultValue: "false" },
      { name: "retire-earlier", type: "bool", defaultValue: "false" },
      { name: "deal-debt", type: "bool", defaultValue: "false" },
      { name: "goal", type: "text" },
      { name: "guide", type: "text" },
      { name: "password", type: "text" },
      { name: "name", type: "text" },
      { name: "surname", type: "text" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Users = InferredTypes["users"];
export type UsersRecord = Users & XataRecord;

export type DatabaseSchema = {
  users: UsersRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Darlington-John-s-workspace-ju0kd2.us-east-1.xata.sh/db/darlington-fruitful",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
